name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: SonarQube Scan
        run: mvn sonar:sonar

      - name: Build Docker Image
        run: |
          docker build -t your-docker-image-name .
          docker tag your-docker-image-name:latest your-ecr-repo-uri:latest
          echo "${{ secrets.ECR_PASSWORD }}" | docker login --username AWS --password-stdin your-ecr-repo-uri
          docker push your-ecr-repo-uri:latest

      - name: Deploy to EKS
        run: kubectl apply -f deployment.yaml
